### ISSUE TITLE
Crash to desktop without logged error

### ISSUE THREAD

**Issue by Entoarox** [Entoarox/StardewMods#16]
Change in code added during https://github.com/Entoarox/StardewMods/compare/2652dd64db787add81130855fefd7f330d28050b...687a212fbe51536685cc6f76dee1c1d641350f7

Most likely culprit the SerializableDictionary override.

Computer details of reporter requested but not yet received.

**Comment by kurotetsuka** [comment]
Heya, I seem to be encountering this error. (Linux, latest version of SDV and SMAPI)

I can get it to happen in two ways:

 - if there are saves, click the load button on the main menu. Ctd after a second or so.
 - if there are no saves, start a new game. Ctd after the `Saving...` screen.

I can also confirm that the crash happens on versions 1.6.2 and 1.6.3, but not 1.6.1 - which I'm running at the moment with no noticable issues. Lemme know if I there's more info you need or if you'd like me to help test.

**Comment by Entoarox** [comment]
Serializable override this issue references has not been in place for a long time now, closing this.
