### ISSUE TITLE
New xnbs not loaded properly through Xnb Loader when ALL is present

### ISSUE THREAD

**Issue by Acerbicon** [Entoarox/StardewMods#22]
As the title states, my farm overhauls include a new (seasonal) tilesheet. I thought at first it was just Xnb Loader not loading it, but when I looked at the error log I noticed ALL reporting about it so I took it out and it loaded fine. I guess ALL preempts Xnb Loader and causes issues.

(https://github.com/Entoarox/StardewMods/files/848033/MODDED_ProgramLog.Log_LATEST.txt)

**Comment by Entoarox** [comment]
Woops, looks like I did not take into account XnbLoader's mechanic when setting up the sanity checks in ALL, no wonder, since they are ancient in comparison!

**Comment by Entoarox** [comment]
Closing this, can be reopened if the bug still persists at the current time.
