### ISSUE TITLE
More Animals naming menu doesn't work with controller

### ISSUE THREAD

**Issue by Pathoschild** [Entoarox/StardewMods#59]
If you use a controller to interact with the pet box, when you choose to adopt the naming screen appears for a fraction of a second then returns to the adoption question. It works fine when using a mouse instead.

[Reported on Nexus](https://www.nexusmods.com/stardewvalley/mods/2274/?tab=posts&jump_to_comment=66415611).

**Comment by Entoarox** [comment]
Why are there still people using controllers with mods on the PC version? >_<
You're stuck with using a keyboard in the end anyway because a controller doesnt have enough buttons :S

You are welcome to try looking into it pathos, but the relevant code is all CA's, so fixing it would be difficult...

**Comment by Pathoschild** [comment]
Fixed in `develop` for the next More Animals release, with a secondary fix in the upcoming SMAPI 2.11.

**Comment by jackmaster9000** [comment]
> Why are there still people using controllers with mods on the PC version? >_<
> You're stuck with using a keyboard in the end anyway because a controller doesnt have enough buttons :S


Why Not the game is not a FPS this style of game is best played with a controller but i don't expect people that play on PC not to use a controller but to consider thay might

**Comment by Entoarox** [comment]
@jackmaster9000 I'm not saying they cant use a controller, I'm saying that doing so with mods is pointless because a controller doesnt have enough buttons to assign every mod hotkey, forcing you to use a keyboard *anyway*.

**Comment by jackmaster9000** [comment]
@Entoarox i under sand that and u can if u thank about the use of 2 or more buttons at the same time like Up and A button or RT and LT there is plenty ways to get around controller limitations
