### ISSUE TITLE
"year>1" condition

### ISSUE THREAD

**Issue by Androxilogin** [Entoarox/StardewMods#7]
{
      "MapName": "SeedShop",
      "LayerId": "Front",
      "TileX": 40,
      "TileY": 7,
      "TileIndex": -1,
	  "Conditions": "year>2",
      "Optional": false
    },

/ This is expected to remove the Joja note graphic from Pierre's. Instead it gives an error with no result.

[11:58:29 ERROR Advanced Location Loader] Tile `Tile(SeedShop@[40,7]:Front = `-1`)` Condition Error: The `!year>0` and `$2` conditions cannot be used at the same time

This displays that these two conditions are conflicting, however only 'year>2' is present in the manifest.

[SeedShop Year Condition.txt](https://github.com/Entoarox/StardewMods/files/717343/SeedShop.Year.Condition.txt)

**Comment by Entoarox** [comment]
Related to #6, closed until #6 is solved.
