### ISSUE TITLE
Seasonal tilesheets with non-seasonal attributes 

### ISSUE THREAD

**Issue by Androxilogin** [Entoarox/StardewMods#8]
When using a tilesheet that has the ability for seasonal counterparts but set to '"Seasonal": false' so to load only from one tilesheet to a specified map, this will display tile errors. Not sure if this is an error or even preventable.

    {
	  "MapName": "SeedShop",
	  "FileName": "SeedShop",
	  "SheetId": "additions",
	  "Seasonal": false
	},
	{
	  "MapName": "Forest",
	  "FileName": "Forest",
	  "SheetId": "additions",
	  "Seasonal": true
	}

**Comment by Entoarox** [comment]
@Androxilogin Question, in the first case, SeedShop, does `SeedShop.xnb` exist, and do all 4 `Forest_<season>.xnb` files exist for the second? The same sheet Id being used for 2 separate files in 2 separate locations should have no effect.

**Comment by Androxilogin** [comment]
Your first question, when you say _exist_ do you mean set as an override? If so, yes.

I suppose I didn't exactly clarify the issue properly. I apologize, running through things to generate a report. These were from the same manifest. The 4 seasons do exist and function properly however the problem is that using **also** a non-seasonal setting to another map will not work even with a defined (additions_spring.xnb) season. It's not a big concern, just a chance to use less tilesheets.

**Comment by Entoarox** [comment]
You have `SheetId` as "additions", not `FileName`, it is `FileName` that references the xnb file for the tilesheet.

But if I understand, you have a xnb file called `additions_<season>.xnb` for each season, correct?
In that case, when adding it as a non-seasonal tilesheet, you need to specify the season in the FileName (`additions_spring` for example)
The `Seasonal` flag means that ALL will automatically append `_<season>` to the FileName and updates the sheet each season to reference the new season.

**Comment by Androxilogin** [comment]
Yes, I tried references to specified seasons as well but that was before all of these later updates so this may actually be resolved. Having it seasonal on one map and use a single sheet on another simul. shouldn't be a problem though, correct? (When written in the manifest correctly, anyway).

**Comment by Entoarox** [comment]
No it shouldnt, provided you tell *what* seasonal version to use in the non-seasonal map, since the whole seasonal system is about adding a _<season> suffix and updating the seasonal tilesheets each season, while non-seasonal tilesheets are left as-is, no addition to the name or updating during any time the game is active.

**Comment by Entoarox** [comment]
Closing this as resolved.
