### ISSUE TITLE
Framework 2.5.4 breaks loading save files

### ISSUE THREAD

**Issue by rikai** [Entoarox/StardewMods#85]
Hello, updated to 2.5.4 this morning and loading my existing save breaks:

https://smapi.io/log/fe8abda3d577404f81fb7c84135ab99a

Reverting to 2.5.3 allows the save to load.

Based on the log, it may be a conflict with SpaceCore, but I'm really not sure?

**Comment by Entoarox** [comment]
Issue is a NRE in the loading override by space, I am assuming that EF replacing the serializer prevents this NRE in spaceCore from happening, so probably not a EF bug so much as a SpaceCore bug that older versions of EF hid.

Please try loading without EF at all, and if the bug persists, then this is truly a issue with the latest SpaceCore release.

**Comment by rikai** [comment]
Hey! I have tried both loading without the framework while still having SpaceCore (the issue does not happen) as well as loading with the previous version of the framework while still having SpaceCore.

The issue does not appear in either case. It is only with 2.5.4 that this issue appears as far as I can tell.

**Comment by Entoarox** [comment]
Issue has been identified and fixed in 2.5.5
